version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api/v1
      - VITE_SOCKET_URL=http://localhost:3000
      - VITE_APP_NAME=Betting Payment Manager
    restart: unless-stopped
    networks:
      - betting-network

networks:
  betting-network:
    driver: bridge

